version: '2.1'

volumes:
  files:
    driver: local
  htdocs:
    driver: local
  mysql:
    driver: local
  backup:
    driver: local

services:
  wordpress:
    image: owncloud/wordpress:${WORDPRESS_VERSION}
    restart: always
    ports:
      - ${HTTPS_PORT}:443
      - ${HTTP_PORT}:80
    depends_on:
      - db
    environment:
      - WORDPRESS_DOMAIN=${WORDPRESS_DOMAIN}
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USERNAME=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_HOST=db
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - files:/mnt/data
      - htdocs:/var/www/wordpress

  db:
    image: webhippie/mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=wordpress
      - MARIADB_USERNAME=wordpress
      - MARIADB_PASSWORD=wordpress
      - MARIADB_DATABASE=wordpress
      - MARIADB_MAX_ALLOWED_PACKET=128M
      - MARIADB_INNODB_LOG_FILE_SIZE=64M
      - MARIADB_INNODB_LARGE_PREFIX=ON
      - MARIADB_INNODB_FILE_FORMAT=Barracuda
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - mysql:/var/lib/mysql
      - backup:/var/lib/backup
