#!/usr/bin/env bash

declare -x WORDPRESS_MAIL_HOST
[[ -z "${WORDPRESS_MAIL_HOST}" ]] && WORDPRESS_MAIL_HOST="mail.owncloud.com"

declare -x WORDPRESS_MAIL_PORT
[[ -z "${WORDPRESS_MAIL_PORT}" ]] && WORDPRESS_MAIL_PORT=""

declare -x WORDPRESS_MAIL_USERNAME
[[ -z "${WORDPRESS_MAIL_USERNAME}" ]] && WORDPRESS_MAIL_USERNAME=""

declare -x WORDPRESS_MAIL_PASSWORD
[[ -z "${WORDPRESS_MAIL_PASSWORD}" ]] && WORDPRESS_MAIL_PASSWORD=""

declare -x WORDPRESS_MAIL_SECURITY
[[ -z "${WORDPRESS_MAIL_SECURITY}" ]] && WORDPRESS_MAIL_SECURITY="ssl"

declare -x WORDPRESS_MAIL_FROM
[[ -z "${WORDPRESS_MAIL_FROM}" ]] && WORDPRESS_MAIL_FROM="norepy@owncloud.com"

declare -x WORDPRESS_MAIL_NAME
[[ -z "${WORDPRESS_MAIL_NAME}" ]] && WORDPRESS_MAIL_NAME="WordPress Admin"

true
