#!/usr/bin/env bash

declare -x WORDPRESS_VOLUME_ROOT
[[ -z "${WORDPRESS_VOLUME_ROOT}" ]] && WORDPRESS_VOLUME_ROOT="/mnt/data"

declare -x WORDPRESS_VOLUME_CERTS
[[ -z "${WORDPRESS_VOLUME_CERTS}" ]] && WORDPRESS_VOLUME_CERTS="${WORDPRESS_VOLUME_ROOT}/certs"

declare -x WORDPRESS_VOLUME_SESSIONS
[[ -z "${WORDPRESS_VOLUME_SESSIONS}" ]] && WORDPRESS_VOLUME_SESSIONS="${WORDPRESS_VOLUME_ROOT}/sessions"

true
